package com.samuel.readaloud.repository

import android.content.Context
import android.speech.tts.TextToSpeech
import android.util.Log
import com.chaquo.python.Python
import com.samuel.readaloud.data.local.PreferenceManager
import com.samuel.readaloud.model.Voice
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import org.json.JSONArray
import java.io.File
import java.util.Locale
import kotlin.coroutines.resume

class TtsRepository(private val context: Context) {

    private val pythonModule by lazy {
        Python.getInstance().getModule("tts_engine")
    }

    suspend fun getVoices(provider: String): List<Voice> {
        return if (provider == PreferenceManager.PROVIDER_SYSTEM) {
            getSystemVoices()
        } else {
            withContext(Dispatchers.IO) {
                val jsonString = pythonModule.callAttr("get_voices_json", provider).toString()
                parseVoices(jsonString)
            }
        }
    }

    private suspend fun getSystemVoices(): List<Voice> = suspendCancellableCoroutine { cont ->
        var tts: TextToSpeech? = null
        tts = TextToSpeech(context) { status ->
            if (status == TextToSpeech.SUCCESS) {
                try {
                    val voices = tts?.voices?.map { voice ->
                        Voice(
                            name = "${voice.locale.displayLanguage} (${voice.name})",
                            shortName = voice.name,
                            gender = "Unknown",
                            locale = voice.locale.toLanguageTag()
                        )
                    }?.sortedBy { it.locale } ?: emptyList()

                    if (cont.isActive) cont.resume(voices)
                } catch (e: Exception) {
                    Log.e("TtsRepository", "Error fetching system voices", e)
                    if (cont.isActive) cont.resume(emptyList())
                } finally {
                    tts?.shutdown()
                }
            } else {
                Log.e("TtsRepository", "Failed to initialize System TTS")
                if (cont.isActive) cont.resume(emptyList())
            }
        }
    }

    suspend fun generateAudio(
        text: String,
        voiceShortName: String,
        outputFile: File,
        provider: String
    ): Result<Pair<File, File>> = withContext(Dispatchers.IO) {
        // System TTS does not use this generation pipeline
        if (provider == PreferenceManager.PROVIDER_SYSTEM) {
            return@withContext Result.failure(Exception("System TTS uses streaming, not file generation."))
        }

        try {
            Log.d("TtsRepository", "Generating audio... (Length: ${text.length}) Provider: $provider")
            // Pass provider to Python
            pythonModule.callAttr("tts", text, voiceShortName, outputFile.absolutePath, provider)

            val srtFile = File(outputFile.absolutePath + ".srt")
            if (srtFile.exists()) {
                Result.success(Pair(outputFile, srtFile))
            } else {
                Result.failure(Exception("SRT file not generated by Python backend"))
            }
        } catch (e: Exception) {
            Log.e("TtsRepository", "Generation Failed", e)
            Result.failure(e)
        }
    }

    private fun parseVoices(jsonString: String): List<Voice> {
        val voiceList = mutableListOf<Voice>()
        try {
            val jsonArray = JSONArray(jsonString)
            for (i in 0 until jsonArray.length()) {
                val obj = jsonArray.getJSONObject(i)
                val shortName = obj.optString("ShortName").takeIf { it.isNotBlank() } ?: ""
                val friendlyName = obj.optString("FriendlyName").takeIf { it.isNotBlank() } ?: shortName
                val locale = obj.optString("Locale").ifBlank { "Unknown" }

                if (shortName.isNotBlank()) {
                    voiceList.add(Voice(friendlyName, shortName, "Unknown", locale))
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return voiceList
    }
}